# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file
version: '3'
services:

  user-mysql:
     image: mysql:5.7
     network_mode: host
     ports:
       - "3307:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_PASSWORD: aditya.verma998
       MYSQL_DATABASE: authenticationservicedb
       MYSQL_HOST: localhost
  user-mongo:
     image: mongo
     network_mode: host
     ports:
       - "27017:27017"
     environment:
       MONGO_DATABASE: UserServiceDB
       MONGO_PORT: 27017
       MONGO_HOST: localhost

  userauthentication-service:
     image: userauthentication-service
     build: 
       context: userauthentication-service/
     depends_on:
       - user-mysql
     ports:
       - "8081:8081"
     network_mode: host
     restart: always
  userservice:
     image: userservice
     build: 
       context: userservice/
     depends_on:
       - user-mongo
     ports:
       - "8082:8082"
     network_mode: host
     restart: always
  noteservice:
     image: noteservice
     build: 
       context: noteservice/
     depends_on:
       - user-mongo
     ports:
       - "8083:8083"
     network_mode: host
     restart: always
