spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authenticationservicedb?autoReconnect=true&useSSL=false
    username: root
    password: aditya.verma998
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
